name: dbt CI pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
    run_dbt_jobs:

      runs-on: ubuntu-latest

      steps:
        - name: Checkout code
          uses: actions/checkout@v4

        - name: build docker image
          run: docker build -t netflix-dbt-pipeline .

        - name: run dbt build inside docker
          run: docker run --rm netflix-dbt-pipeline